//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuanThuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CHITIETDONHANG
    {
        [DisplayName("Mã đơn hàng")]
        public int MADH { get; set; }
        [DisplayName("Mã sản phẩm")]
        [Required]

        public int MASP { get; set; }
        [Required]
        [DisplayName("Số lượng")]

        public Nullable<int> SOLUONG { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
