//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuanThuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
        [DisplayName("Mã đơn hàng")]

        public int MADH { get; set; }
        [DisplayName("Mã khách hàng")]

        public Nullable<int> MAKH { get; set; }
        [DisplayName("Trạng thái")]
        [Required]
        public string TRANGTHAI { get; set; }
        [DisplayName("Địa chỉ giao")]
        [Required]
        public string DIACHIGIAO { get; set; }
        [DisplayName("Số điện thoại")]
        [Required]
        public string SDT { get; set; }
        [DisplayName("Trạng đặt")]
        [Required]
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        [DisplayName("Ngày giao")]
        [Required]
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        [DisplayName("Mô tả")]
        [Required]
        public string MOTA { get; set; }
        [DisplayName("Tổng tiền")]
        [Required]
        public Nullable<double> TONGTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
