//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuanThuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LOAITK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAITK()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
        [DisplayName("Mã loại tài khoản")]

        public string MALOAITK { get; set; }
        [DisplayName("Tên loại tài khoản")]

        public string TENLOAITK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
