//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuanThuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }

        [DisplayName("Mã sản phẩm")]

        public int MASP { get; set; }
        [Required]
        [DisplayName("Tên loại sản phẩm")]

        public string TENSP { get; set; }
        [Required]
        [DisplayName("Hình nhỏ")]

        public string HINHNHO { get; set; }
        [Required]
        [DisplayName("Mô tả")]

        public string MOTA { get; set; }
        [Required]
        [DisplayName("Mã thương hiệu")]

        public Nullable<int> MATH { get; set; }
        [Required]
        [DisplayName("Đánh giá")]

        public string DANHGIA { get; set; }
        [Required]
        [DisplayName("Hình lớn")]

        public string HINHLON { get; set; }
        [Required]
        [DisplayName("Số lượng")]

        public Nullable<int> SOLUONG { get; set; }
       

        public string MALOAISP { get; set; }
        [Required]
        [DisplayName("Đơn giá")]

        public Nullable<double> DONGIA { get; set; }
        [DisplayName("Mã khuyến mãi")]

        public Nullable<int> MAKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
