//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuanThuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.DONHANGs = new HashSet<DONHANG>();
            this.Hoadons = new HashSet<Hoadon>();
        }
    
        public int MASP { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string TENSP { get; set; }
        [Required]

        [DisplayName("Hình nhỏ")]
        public string HINHNHO { get; set; }
        [DisplayName("Mô tả")]
        public string MOTA { get; set; }
        [DisplayName("Mã thương hiệu")]
        public Nullable<int> MATH { get; set; }
        [DisplayName("Hình lớn")]
        [Required]

        public string HINHLON { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> SOLUONG { get; set; }
        [DisplayName("Mã loại sản phẩm")]
        public string MALOAISP { get; set; }
        [DisplayName("Đơn giá")]
        public Nullable<double> DONGIA { get; set; }
        [DisplayName("Mã khuyến mãi")]

        public Nullable<int> MAKM { get; set; }
        [DisplayName("Giá seller")]

        public Nullable<double> GIASELLER { get; set; }
        [DisplayName("Đánh gia")]

        public string DANHGIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoadon> Hoadons { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
