//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuanThuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
        [DisplayName("Mã tài khoản")]
        [Required]
        public int MATK { get; set; }
        [DisplayName("Tên đăng nhập")]
        [Required(ErrorMessage = "Nhập tên người dùng")]
        public string TENDN { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage ="Chưa nhập mật khẩu")]
        public string MATKHAU { get; set; }
        [DisplayName("Ngày đăng ký")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> TRANGTHAI { get; set; }
        [DisplayName("Mã loại tài khoản")]
        [Required]
        public string MALOAITK { get; set; }
        [DisplayName("Email")]
        [Required]
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
        public virtual LOAITK LOAITK { get; set; }
    }
}
