//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuanThuctap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class THUONGHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUONGHIEU()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
        [DisplayName("Mã thương hiệu")]
        public int MATH { get; set; }
        [Required(ErrorMessage ="Chưa nhập tên thương hiệu")]
        [DisplayName("Tên thương hiệu")]
        public string TENTH { get; set; }
        [Required(ErrorMessage = "Chưa nhập hình thương hiệu")]
        [DisplayName("Hình thương hiệu")]

        public string HINHTH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
